ARG FROM_IMAGE=jahia/cimg-mvn-cache:cimg_openjdk_8.0.312-node
ARG CCI_SRC_IMAGE=cimg/openjdk:8.0.312-node

FROM $FROM_IMAGE as warmed-up-image

USER root

RUN mv /home/circleci/.m2 /root/; \
    chown -R root:root /root/.m2

# Using a multi-stage build to reduce the overall image size
FROM $CCI_SRC_IMAGE

USER root

COPY --from=warmed-up-image /root/ /root/
