name: Nightly run

on:
  schedule:
    - cron:  "0 0 * * *"
    filters:
      branches:
        only:
         - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: user/app:latest