name: On Code Change

on: [push]

env:
  cci_src_image: cimg/openjdk:8.0.312-node
  PRIMARY_RELEASE_BRANCH: main

jobs:
  build:
    name: Buid and push Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Creating tag from CircleCI image
        shell: bash
        run: |
          echo "CCI_SRC_IMAGE=${{ env.cci_src_image }}" >> $GITHUB_ENV
          echo "JAHIA_TAG=$(echo ${{ env.cci_src_image }} | sed -r 's/[:\/]+/_/g')" >> $GITHUB_ENV
      - name: Printing CircleCI image tags
        shell: bash
        run: |
          echo "CCI_SRC_IMAGE=${CCI_SRC_IMAGE}"
          echo "JAHIA_TAG=${JAHIA_TAG}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: | 
            ${{ secrets.BASTION_SSH_PRIVATE_KEY_JAHIACI }}
            ${{ secrets.GH_SSH_PRIVATE_KEY_JAHIACI }}
      - name: Build and push CircleCI Docker image
        uses: docker/build-push-action@v3
        with:
          push: false #!e "${BRANCH_NAME} == ${{ env.PRIMARY_RELEASE_BRANCH }} ? true : false"
          tags: jahia/cimg-mvn-cache:$JAHIA_TAG
      - name: Build and push Github Actions Docker image
        shell: bash
        run: |
          docker build -t jahia/cimg-mvn-cache:ga_$JAHIA_TAG \
          --build-arg CCI_SRC_IMAGE="$CCI_SRC_IMAGE" \
          --build-arg FROM_IMAGE="jahia/cimg-mvn-cache:$JAHIA_TAG" \
          -f Dockerfile-github .

          if [[ "${BRANCH_NAME}" == "${{ env.PRIMARY_RELEASE_BRANCH }}" ]]; then
            docker push jahia/cimg-mvn-cache:ga_$JAHIA_TAG
          else
            echo "Not in the main branch, skipping docker push"
          fi